#!/usr/bin/python
import ChunkServer, gevent.server, rpc, gevent
import logging, config, util, sys, os.path

header="""Chunk Server of SoftSAN
Usage: chkserv-cli [options]
options:"""

cfgstruct = (\
	('address',			'a',	'0.0.0.0',			'IP address to bind'), \
	('port',			'p',	0x2121,				'TCP port to bind'), \
	('mdsaddress',		'M',	'127.0.0.1',			'meta data server address'), \
	('mdsport',			'm',	0x26505,				'meta data server TCP port'), \
	('vg',				'g',	'SANGroup',			'name of volume group for use exclusively by SoftSAN'),\
	('volprefix',		'z',	'lv_softsan_',		'prefix of volume name'),\
	('logging-level',	'l',	'info',				'logging level, can be "debug", "info", "warning", "error" or "critical"'), \
	('logging-file',	'f',	'stdout',			'logging appends to this file'),\
	('config',			'c',	'Chunkserver.conf',	'config file'),\
	('help',			'h',	False,				'this help'),\

)

try:
	configure,_ = config.config(cfgstruct, 'config')
	confobj = util.Object(configure)
except:
	pass

if configure['help']==True:
	print header
	config.usage_print(cfgstruct)
	exit(0)

util.setupLogging(configure)
server=ChunkServer.ChunkServer()
gevent.spawn(server.heartBeat, confobj)
service=rpc.RpcService(server)
endpoint=(configure['address'], int(configure['port']))
framework=gevent.server.StreamServer(endpoint, service.handler)
framework.serve_forever()